version: '3'

services: 
    backend:
        container_name: nba-app-backend
        restart: always
        build: .
        ports:
            - '5000:5000'
    frontend:
        container_name: nba-app-frontend
        restart: always
        build: ./client
        ports:
            - '80:3000'
        links:
            - backend