const abr = {
  "ATL" : "atl",
  "BKN" : "bkn",
  "BOS" : "bos",
  "CHA" : "cha",
  "CHI" : "chi",
  "CLE" : "cle",
  "DAL" : "dal",
  "DEN" : "den",
  "DET" : "det",
  "GSW" : "gs",
  "HOU" : "hou",
  "IND" : "ind",
  "LAC" : "lac",
  "LAL" : "lal",
  "MEM" : "mem",
  "MIA" : "mia",
  "MIL" : "mil",
  "MIN" : "min",
  "NOP" : "no",
  "NYK" : "nyk",
  "OKC" : "okc",
  "ORL" : "orl",
  "PHI" : "phi",
  "PHX" : "phx",
  "POR" : "por",
  "SAC" : "sac",
  "SAS" : "sas",
  "TOR" : "tor",
  "UTA" : "uth",
  "WAS" : "was"
}

module.exports = abr